### ISSUE TITLE
Requiring modules in functions causes them unable to be used with mocked filesystem

### ISSUE THREAD

**Issue by xavdid** [heroku/node-heroku-client#71]
Hello again!

So after updating `heroku-cli-util` to v6 (which bumped this module req to `v3beta`) a couple of tests started failing (see Travis [build](https://travis-ci.org/xavdid/heroku-config/builds/140179426#L431)) because internal modules couldn't be found. 

Turns out the source is lines like [this](https://github.com/heroku/node-heroku-client/blob/master/index.js#L9) where modules are required in functions. I extensively mock the filesystem (using [mock-fs](https://github.com/tschaub/mock-fs)). Since the `require`s happen in functions, there's no point where we can make http requests when the fs mock is active.

Per this fairly well-starred node [best practices guide](https://github.com/alanjames1987/Node.js-Best-Practices#never-require-modules-inside-of-functions), developers should refrain from requiring modules in functions. While it does speed up initial load time (because it only runs synchronous code if and when the function is actually used), it has unexpected consequences down the line. 

Looking at the code, the best solution seems to be requiring everything at the top of the file, like most node projects. Is that something you'd be open to?

**Comment by dickeyxxx** [comment]
So most node apps are services where initial load time isn't very important, but optimizing that and lazy loading only what is needed for a CLI is crucial. So I don't think I'd like to move back to requiring all the modules at the top of the file. Some, like for proxies, are only loaded if the user actually configured a proxy.

I would suggest using proxyquire instead of mock-fs. Then you can mock out requires, but it'll still work with them in functions.

**Comment by xavdid** [comment]
That's sort of the opposite of my issue. I need a mocked filesystem (or location, at least) for the test to simulate reading from a default or user defined file). If I globally mock `require` (their docs [here](https://github.com/thlorenz/proxyquire#globally-override-require)), then the calls in this `index.js` would just fail, ie `var Request = require('./lib/request')`. I need external code to work normally so I can test this module, if that makes sense.

**Comment by dickeyxxx** [comment]
ah I see, I checked out your tests and I see what you mean. I looked into it a bit but unfortunately I'm not sure what the best path forward is. `heroku-cli-util` also uses a lot of lazy-loading and adding that in greatly reduced the load time of the CLI by a couple hundred milliseconds, so I definitely don't want to move away from that.

I realize this is annoying since you've already written the test code, but maybe the best thing to do would be to actually write out to the file system and read the files back in as an integration test? Or if `mock-fs` has a solution from your issue you posted.

**Comment by xavdid** [comment]
Yeah for sure. Rewriting the tests isn't a huge deal since it's only 2 of
them, but they are the full end to end, so I want to make sure they work.

I've filed an issue on their end to see if there's a half-mock option or
something. Actually writing the files isn't a bad idea though, I'll credit
it out.

Thanks!

~DavidB
[davidbrownman.com]
c: 303.819.0850
